aws_region           = "ap-south-1"
artifact_bucket      = "your-artifact-bucket-name"
source_bucket_name   = "source-bucket-swatha17"
destination_bucket_name = "destination-bucket-swatha17"
notification_email   = "swatha.manoharan@bootlabstech.com"
lambda_function_name = "csv-to-parquet-processor"
layer_name           = "csv-to-parquet-layer"
