name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Create pandas Lambda Layer
        run: |
          mkdir -p layer1/python
          pip install boto3 -t layer1/python --no-cache-dir
          zip -r layer1.zip layer1
          rm -rf layer1

      - name: Create pyarrow Lambda Layer
        run: |
          mkdir -p layer2/python
          pip install pyarrow -t layer2/python --no-cache-dir
          zip -r layer2.zip layer2
          rm -rf layer2


      - name: Zip Lambda Function
        run: |
          zip lambda_function_payload.zip lambda_function.py

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Move ZIP files to Terraform folder
   
        run: |
            mv lambda_function_payload.zip layer1.zip layer2.zip terraform/

      - name: Terraform Apply (Infra + Lambda + Layer)
        run: |
          cd terraform
          terraform apply -auto-approve
