name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies for Lambda Layer
        run: |
          mkdir -p python
          pip install -r requirements.txt -t python/
          zip -r layer.zip python

      - name: Zip Lambda function code
        run: zip -r lambda.zip lambda_function/lambda_function.py


      - name: Upload Lambda Layer to S3
        run: aws s3 cp layer.zip s3://${{ secrets.ARTIFACT_BUCKET }}/layer.zip

      - name: Upload Lambda Code to S3
        run: aws s3 cp lambda.zip s3://${{ secrets.ARTIFACT_BUCKET }}/lambda.zip

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
